Update Scripts

diff --git a/cse30342-run-docker b/cse30342-run-docker
--- a/cse30342-run-docker
+++ b/cse30342-run-docker
@@ -159,6 +159,11 @@ elif test -x /bin/netstat; then
     fi
 fi
 
+if test -z "$maindir"; then
+    echo "Error: could not determine your directory."
+    exit 1
+fi
+
 has_network || create_network
 
 if $clean; then
